apiVersion: v1
kind: Pod
metadata:
  name: pi-py
  namespace: basic-spark
spec:
  containers:
  - args:
    - driver
    - --properties-file
    - /opt/spark/conf/spark.properties
    - --class
    - org.apache.spark.deploy.PythonRunner
    - local:///opt/bitnami/spark/examples/src/main/python/pi.py
    - "10"
    env:
    - name: SPARK_USER
      value: spark
    - name: SPARK_APPLICATION_ID
      value: spark-5825271c9732468eac86c71b0f114d72
    - name: SPARK_MASTER_URL
      value: spark://basic-spark-master-svc:7077
    - name: SPARK_DRIVER_BIND_ADDRESS
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    image: bitnami/spark:3.5.0-debian-11-r21
    imagePullPolicy: IfNotPresent
    name: spark-kubernetes-driver
    ports:
    - containerPort: 7078
      name: driver-rpc-port
      protocol: TCP
    - containerPort: 7079
      name: blockmanager
      protocol: TCP
    - containerPort: 4040
      name: spark-ui
      protocol: TCP

  serviceAccount: spark
  serviceAccountName: spark
  