apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags-pv-volume
  labels:
    type: local
spec:
  storageClassName: dags
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/host/d/cluster-dags"
